<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Generate Stickers</title>
		<%@include file="../includes/HeadScript.jsp"%>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
		<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
		<!-- DataTables -->
		<link rel="stylesheet" href="${contextPath}/resources/dist/plugins/datatables/css/dataTables.bootstrap.min.css">
        <!-- SweetAlert2 -->
        <link rel="stylesheet" href="${contextPath}/resources/dist/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css">				
		<style type="text/css">
			.table-sm>tbody>tr>td, .table>tfoot>tr>td {
			    border-top: 1px solid #f4f4f4;
			    border-bottom: 1px solid #f4f4f4;
			}
			.showUpdated {
				color: #0c5460 !important;
				background-color: #bee5eb !important;
			}				
		</style>		
	</head>
	<body class="skin-blue sidebar-mini">
		<div class="wrapper boxed-wrapper">
			<%@include file="../includes/Header.jsp"%>
			<%@include file="../includes/Sidebar.jsp"%>
			<!-- Content Wrapper. Contains page content -->
			<div class="content-wrapper">
				<!-- Content Header (Page header) -->
				<div class="content-header sty-one">
					<h1>Generate Stickers</h1>
				</div>
				<!-- Main content -->
				<div class="content">
					<div class="card">
						<div class="card-body">
							<c:if test="${not empty patientId}">
								<%@include file="IncludePatientDetails.jsp"%>
								<Br>				
							</c:if>
							<form  action="${contextPath}/diet/generate-stickers" method="GET" onsubmit="return Validation();" id="stickersForm" target="_blank">
								<input type="hidden" name="patientId" value="${patientId}"/>
								<div class="row">
									<c:if test="${empty patientId}">
									<div class="col-lg-4">
										<fieldset class="form-group">
											<label for="dietType">Diet Type</label><span class="text-danger">*</span>
											<select class="form-control selectpicker" id="dietType" name="dietType" data-size="10" onchange="dietTypeChange();">
												<option value="1">Diet Type Solid</option>
												<option value="2">Diet Type Liquid Oral/TF</option>
											</select>
										</fieldset>
									</div>
									</c:if>
									<div class="col-lg-4">
										<fieldset class="form-group">
											<label for="medicalComorbidities">Service Type</label><span class="text-danger">*</span>
											<select class="form-control selectpicker" id="serviceMasters" name="serviceMasterId" data-live-search="true" data-size="10" onchange="serviceMastersChange();">
												<c:forEach items="${serviceMasterList}" var="serviceMasters">
													<option class="serviceMasters_option" value="${serviceMasters.serviceMasterId}">${serviceMasters.service}</option>
												</c:forEach>
											</select>
										</fieldset>
									</div>
								</div>
								<button type="submit" class="btn btn-success waves-effect waves-light">Generate Stickers</button>								
							</form>
						</div>
					</div>				
				</div>
				<!-- /.content --> 
			</div>
			<!-- /.content-wrapper -->
			<footer class="main-footer">
				*generated by Nutriment and date & time of printing
			</footer>			
			<%@include file="../includes/Footer.jsp"%>
		</div>
		<!-- ./wrapper --> 
		<%@include file="../includes/FooterScript.jsp"%>
		<script src="${contextPath}/resources/dist/plugins/jquery-validation-1.19.3/dist/jquery.validate.js"></script>
		<script src="${contextPath}/resources/dist/plugins/moment/min/moment.min.js"></script>
		<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

        <!-- SweetAlert2 -->
        <script src="${contextPath}/resources/dist/plugins/sweetalert2/sweetalert2.min.js"></script>			  
		<script type="text/javascript">
		function dietTypeChange() {
			<c:if test="${empty patientId}">
				$("#serviceMasters").val("");
				var validOptions = $("#dietType").val() == "1" ? dietTypeSolid : dietTypeLiquidOralTF;
		        $(".serviceMasters_option").each(function() {
		            if (validOptions.includes($(this).val())) {
		                $(this).show();
		            } else {
		                $(this).hide();
		            }
		        });
	        </c:if>
	        $('.selectpicker').selectpicker('refresh');
		}		
		
		function Validation() {}

		$(document).ready(function() {
		    $("#Stickers").addClass("active");
		    $('.selectpicker').selectpicker(); 
		    dietTypeChange();

		    $("#stickersForm").validate({
		        // in 'rules' user have to specify all the constraints for respective fields
		        rules: {
		        	serviceMasterId: {
		                required: true
		            }
		        },
		        errorPlacement: function(error, element) {
		            if (element.is("select")) {
		                error.insertAfter(element.parent("div"));
		            } else {
		                error.insertAfter(element);
		            }
		        },
		        // in 'messages' user have to specify message as per rules
		        messages: {
		        	serviceMasterId: {
		                required: "Please Select Service Type"
		            }
		        }
		    });
		});
		</script>    	
	</body>
</html>